platform :ios, "7.0"

pod 'libextobjc/EXTScope'
pod 'UIView+FDCollapsibleConstraints'
pod 'YYKit'
pod 'KVOController'
pod 'Mantle', '~> 1.5.7'
pod 'SDVersion'
pod 'SDRecordButton'
pod 'UIAlertView+Blocks'
pod 'UIActionSheet+Blocks'
